### ISSUE TITLE
Implement management of approval profiles

### ISSUE THREAD

**Issue by lubomirw** [3KeyCompany/CZERTAINLY-Core#482]
Implement approval profiles that defines approval process for actions that needs to be approved. Approval profile can then be assigned to RA profile and its actions (issue, renew, revoke certificate, etc.)

`Approval profile`
- expiry time in days for approvals of approval profile
- approval can be defined with more steps - for example someone from group IT should approve, and after that manager user
- approval step can define if approval is required from specific user, role or group. In case of group or role, it is possible to set number of required approvals for step (default 1).
- edit of approval profile creates new version
  - incerements actual version
  - add new steps with new version
- delete of approval profile is allowed only when there is no approval referencing it

`Approval`
- represents approval process for specific object and its action
- status is represented by enum with following values: `pending`, `approved`, `rejected`, `expired`

`ApprovalRecipient`
- representing individual approval of user for specific approval and its step

```mermaid
---
title: Approval profiles
---
erDiagram
    ApprovalProfile ||--|{ ApprovalProfileVersion: has
    ApprovalProfile {
        UUID uuid PK
        text name
        bool enabled
        timestamp created_at
    }
    ApprovalProfileVersion ||--o{ Approval: has
    ApprovalProfileVersion ||--|{ ApprovalStep: has
    ApprovalProfileVersion {
        UUID uuid PK
        UUID approval_profile_uuid FK
        text description "NULL"
        int version
        int expiry "NULL"
        timestamp created_at
    }
    ApprovalStep {
        UUID uuid PK
        UUID approval_profile_version_uuid FK
        UUID user_uuid "NULL"
        UUID role_uuid "NULL"
        UUID group_uuid FK "NULL"
        text description "NULL"
        int order
        int required_approvals "NULL"
    }
    Approval {
        UUID uuid PK
        UUID approval_profile_version_uuid FK
        UUID creator_uuid
        UUID object_uuid
        text resource
        text action
        text status
        timestamp created_at
        timestamp approved_at "NULL"
    }
    ApprovalRecipient }o--|| ApprovalStep : belongs
    ApprovalRecipient }|--|| Approval : belongs
    ApprovalRecipient {
        UUID uuid PK
        UUID user_uuid "NULL"
        UUID approval_uuid FK
        UUID approval_step_uuid FK
        text status
        text comment "NULL"
        timestamp approved_at "NULL"
    }
```

**Comment by moro-lukasrejha** [comment]
ApprovalProfile and ApprovalProfileVersion have added audited variables instead of created_at
