### ISSUE TITLE
Small changes in linking certificates produced by renew/rekey

### ISSUE THREAD

**Issue by lubomirw** [3KeyCompany/CZERTAINLY-Core#485]
- populate related certificates in detail DTO with certificates representing certificates for which certificate is source
- when certificate is issued as result of renew/rekey, event history record should state issue certificate
- differentiate between renew and rekey event in event history
- fix additional information for old certificate to store map with - *New Certificate UUID* and *New Certificate Serial Number* values

**Comment by dmaixner-moro** [comment]
+ make source certificate UUID foreign key with on delete set null
