### ISSUE TITLE
Synchronization of user's parameters through KeyCloak and Czertainly

### ISSUE THREAD

**Issue by KaterinaBzatkova** [3KeyCompany/CZERTAINLY-Core#705]
**Describe the bug**

Assume we already have a user registered in Czertainly via AD login. If user parameters (email, name) in AD change, after the user logs in to Czertainly again, the change is visible in KeyCloak, but not in the Czertainly."

**To Reproduce**
1. Log in to Czertainly via AD as a new user
2. Change the user's parameters (email, name) in AD
3. Log in to Czertainly via AD again (as the same user)
4. Go to the user's profile - the change is not reflected here

**Expected behavior**
Changes from AD will be reflected in Czertainly. 

**Versions**
KeyCloak version 21
Czertainly version: 2.11.0

**Comment by 3keyroman** [comment]
Will be enhanced by https://github.com/3KeyCompany/CZERTAINLY-Auth/issues/80
