### ISSUE TITLE
Show button for ASN.1 Structure in certificate detail is disabled.

### ISSUE THREAD

**Issue by KaterinaBzatkova** [3KeyCompany/CZERTAINLY-Core#772]
**Describe the bug**
The **Show** button for ASN.1 Structure in certificate detail is disabled.

**To Reproduce**
Click on Details of any certificates from Certificate Inventory. At the bottom of the page find: **Property**: ASN.1 Structure, **Value**: Show 
The Button Show is disabled.

**Expected behavior**
You are able to click on the **Show** button and see the whole ASN.1 Structure of the selected certificate.

**Screenshots**
![image](https://github.com/3KeyCompany/CZERTAINLY-Core/assets/93907227/15b8b556-675a-4974-bc96-c374d49912f9)

**Czertainly version**: Release 2.12.
Core image: docker.io/3keycompany/czertainly-core:2.12.0
fe-administrator image: docker.io/3keycompany/czertainly-frontend-administrator:2.12.0
browser: Google, Chrome, Microsoft Edge

**Comment by 3keyroman** [comment]
This is not a bug, you do not have configured utils service, therefore this feature is disabled.
